server:
  port: 8888


spring:
  application:
    name: qb-client
  datasource:
    url:  jdbc:mysql://bdm269683585.my3w.com:3306/bdm269683585?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: bdm269683585
    password: bdm269683585
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      host: 119.23.71.201
      prot: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/




#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

#mybatis:
#  type-aliases-package: com.yd.bean
#  mapper-locations: classpath:mapper/*.xml


