spring:
  application:
    name: qb-eureka

server:
  port: 9999


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #是否将eureka自身作为应用注册到eureka注册中心  #在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka



