spring:
  application:
    name: qb-eureka

server:
  port: 9999


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #是否将eureka自身作为应用注册到eureka注册中心,在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
    fetch-registry: false         # 是否从Eureka中获取注册信息，默认为true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka       #Eureka客户端与Eureka服务端进行交互的地址
    #instance:
    #    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    #    ipAddress: 127.0.0.1


