spring:
  application:
    name: qb-eureka

server:
  port: 9999


eureka:
  instance:
    hostname: localhost               #${spring.cloud.client.ipAddress}
    prefer-ip-address: true
    #lease-expiration-duration-in-seconds               #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。默认为90秒,如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。该值至少应该大于leaseRenewalIntervalInSeconds
    #lease-renewal-interval-in-seconds                #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance。除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量。默认30秒
  client:
    register-with-eureka: false   #是否将eureka自身作为应用注册到eureka注册中心,在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
    fetch-registry: false         # 是否从Eureka中获取注册信息，默认为true  由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka       #Eureka客户端与Eureka服务端进行交互的地址
    #instance:
    #    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    #    ipAddress: 127.0.0.1
  #server:
    #enable-self-preservation: false               # 是否开启自我保护模式，默认为true
    #eviction-interval-timer-in-ms:              # 清理无效节点的时间间隔，默认60000毫秒，即60秒
    #renewal-percent-threshold: 0.49              #定义了renews 和renews threshold的比值，默认值为0.85。当server在15分钟内，比值低于percent，即少了15%的微服务心跳，server会进入自我保护状态, 在本机器上测试的时候，可以把比值调低，比如0.49

