server:
  port: 1111

spring:
  application:
    name: qb-zuul


#zuul:
  #routes:
    #test:
      #path: /client/**
      #serviceId: qb-client
      #stripPrefix: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/



